src/Tugel/TugelBundle/Entity/Package.php
<?php

namespace Tugel\TugelBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;

use Tugel\TugelBundle\Model\AbstractPlatform;

/**
 * TugelBundle:Package
 *
 * @ORM\Entity
 * @ORM\Table(
 * 		name = "package",
 * 		options = {"collate" = "utf8_bin"},
 * 		uniqueConstraints = { @ORM\UniqueConstraint(name = "package_unique", columns = {"platform_id", "name"})}
 * )
 */
class Package {

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var \Tugel\TugelBundle\Entity\Platform
	 *
	 * @ORM\ManyToOne(targetEntity="Platform", inversedBy="packages")
	 * @ORM\JoinColumn(name="platform_id", nullable=false)
	 * @JMS\Exclude
	 */
	private $platform;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="name", type="string", length=255, nullable=false)
	 * @JMS\Groups({"Default", "name"})
	 */
	private $name;

	/**
	 * @var \DateTime
	 *
	 * @ORM\Column(name="added_date", type="datetime", nullable=false)
	 */
	private $addedDate;

	/**
	 * @var \DateTime
	 *
	 * @ORM\Column(name="indexed_date", type="datetime", nullable=true)
	 */
	private $indexedDate;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="error", type="integer", nullable=true)
	 * @JMS\Exclude
	 */
	private $error;

	/**
	 * @var boolean
	 *
	 * @ORM\Column(name="new", type="boolean", nullable=false)
	 * @JMS\Exclude
	 */
	private $new;

	/*******************************************************************/

	/**
	 * @var string
	 *
	 * @ORM\Column(name="version", type="string", length=32, nullable=true)
	 */
	private $version;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="version_ref", type="string", length=64, nullable=true)
	 * @JMS\Exclude
	 */
	private $versionReference;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 *
	 * @ORM\ManyToMany(targetEntity="Package", inversedBy="dependencyOf", fetch="EXTRA_LAZY")
	 * @ORM\JoinTable(name="package_dependencies",
	 * 		joinColumns = {@ORM\JoinColumn(name="package_id", referencedColumnName="id")},
	 * 		inverseJoinColumns = {@ORM\JoinColumn(name="depends_on", referencedColumnName="id")}
	 * )
	 * @ORM\OrderBy({"name" = "ASC"})
	 * @JMS\Groups({"details"})
	 */
	private $dependencies;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 *
	 * @ORM\ManyToMany(targetEntity="Package", mappedBy="dependencies", fetch="EXTRA_LAZY")
	 * @ORM\OrderBy({"name" = "ASC"})
	 * @JMS\Exclude
	 */
	private $dependencyOf;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="description", type="text", nullable=true)
	 * @JMS\Groups({"details", "description"})
	 */
	private $description;

	/*******************************************************************/

	/**
	 * @var string
	 *
	 * @ORM\Column(name="license", type="string", length=255, nullable=true)
	 * @JMS\Groups({"details"})
	 */
	private $license;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="classes", type="text", nullable=true)
	 * @JMS\Groups({"details"})
	 */
	private $classes;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="namespaces", type="text", nullable=true)
	 * @JMS\Groups({"details"})
	 */
	private $namespaces;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="languages", type="string", length=1024, nullable=true)
	 */
	private $languages;

	/*******************************************************************/

	/**
	 * @var float
	 *
	 */
	public $_score;

	/**
	 * @var float
	 *
	 */
	public $_percentScore;

	/**
	 * @var array
	 *
	 * @JMS\Exclude
	 */
	public $data;

	/*******************************************************************/

	public function __construct() {
		$this->codeTags = new \Doctrine\Common\Collections\ArrayCollection();
		$this->tags = new \Doctrine\Common\Collections\ArrayCollection();
		$this->dependencies = new \Doctrine\Common\Collections\ArrayCollection();
		$this->dependencyOf = new \Doctrine\Common\Collections\ArrayCollection();
		$this->new = true;
		$this->error = null;
		$this->addedDate = new \DateTime();
	}

	public function __toString() {
		if ($this->version)
			return $this->name . ':' . $this->version;
		else
			return $this->name;
	}

	/**
	 * Get indexed
	 *
	 * @return boolean
	 */
	public function isIndexed() {
		return $this->version && (
			!$this->error || 
			$this->error == AbstractPlatform::ERR_NEEDS_REINDEXING || 
			$this->error == AbstractPlatform::ERR_DOWNLOAD_NOT_FOUND ||
			$this->error == AbstractPlatform::ERR_DOWNLOAD_ERROR
		);
	}

	public function getUrl() {
		return $this->platform->getPlatform()->getPackageUrl($this);
	}

	public function getCachePath() {
		return WEB_DIRECTORY . '../tmp/' . $this->getPlatform()->getName() . '/' . str_replace(':', '_', $this->getName()) . '/';
	}

	public function getCombinedTags() {
		return trim($this->classes . ' ' . $this->namespaces);
	}

	/*******************************************************************/

	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId() {
		return $this->id;
	}

	/*******************************************************************/

	/**
	 * Set platform
	 *
	 * @param \Tugel\TugelBundle\Entity\Platform $platform
	 * @return Package
	 */
	public function setPlatform(\Tugel\TugelBundle\Entity\Platform $platform) {
		$this->platform = $platform;
		return $this;
	}

	/**
	 * Get platform
	 *
	 * @return \Tugel\TugelBundle\Entity\Platform
	 */
	public function getPlatform() {
		return $this->platform;
	}

	/*******************************************************************/

	/**
	 * Set name
	 *
	 * @param string $name
	 * @return Package
	 */
	public function setName($name) {
		$this->name = $name;
		return $this;
	}

	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName() {
		return $this->name;
	}

	/*******************************************************************/

	/**
	 * Set description
	 * @param string $description
	 * @return Format
	 */
	public function setDescription($description) {
		$this->description = $description;
		return $this;
	}

	/**
	 * Get description
	 * @return string
	 */
	public function getDescription() {
		return $this->description;
	}

	/*******************************************************************/

	/**
	 * Set addedDate
	 *
	 * @param \DateTime $addedDate
	 * @return Package
	 */
	public function setAddedDate($addedDate) {
		$this->addedDate = $addedDate;
		return $this;
	}

	/**
	 * Get addedDate
	 *
	 * @return \DateTime
	 */
	public function getAddedDate() {
		return $this->addedDate;
	}

	/*******************************************************************/

	/**
	 * Set new
	 *
	 * @param boolean $new
	 * @return Package
	 */
	public function setNew($new) {
		$this->new = $new;
		return $this;
	}

	/**
	 * Get new
	 *
	 * @return boolean
	 */
	public function getNew() {
		return $this->new;
	}

	/*******************************************************************/

	/**
	 * Set version
	 *
	 * @param string $version
	 * @return Package
	 */
	public function setVersion($version) {
		$this->version = $version;
		return $this;
	}

	/**
	 * Get version
	 *
	 * @return string
	 */
	public function getVersion() {
		return $this->version;
	}

	/*******************************************************************/

	/**
	 * Set version reference
	 *
	 * @param string $versionReference
	 * @return Package
	 */
	public function setVersionReference($versionReference) {
		$this->versionReference = $versionReference;
		return $this;
	}

	/**
	 * Get version reference
	 *
	 * @return string
	 */
	public function getVersionReference() {
		return $this->versionReference;
	}

	/*******************************************************************/

	/**
	 * Set indexedDate
	 *
	 * @param \DateTime $indexedDate
	 * @return Package
	 */
	public function setIndexedDate($indexedDate) {
		$this->indexedDate = $indexedDate;
		return $this;
	}

	/**
	 * Get indexedDate
	 *
	 * @return \DateTime
	 */
	public function getIndexedDate() {
		return $this->indexedDate;
	}

	/*******************************************************************/

	/**
	 * Set error
	 *
	 * @param boolean $error
	 * @return Package
	 */
	public function setError($error) {
		$this->error = $error;
		return $this;
	}

	/**
	 * Get error
	 *
	 * @return integer
	 */
	public function getError() {
		return $this->error;
	}

	/*******************************************************************/

	/**
	 * Set namespaces
	 *
	 * @param string $namespaces
	 * @return Package
	 */
	public function setNamespaces($namespaces) {
		$this->namespaces = $namespaces;
		return $this;
	}

	/**
	 * Get namespaces
	 *
	 * @return string
	 */
	public function getNamespaces() {
		return $this->namespaces;
	}

	/*******************************************************************/

	/**
	 * Set classes
	 *
	 * @param string $classes
	 * @return Package
	 */
	public function setClasses($classes) {
		$this->classes = $classes;
		return $this;
	}

	/**
	 * Get classes
	 *
	 * @return string
	 */
	public function getClasses() {
		return $this->classes;
	}

	/*******************************************************************/

	/**
	 * Set languages
	 *
	 * @param string $languages
	 * @return Package
	 */
	public function setLanguages($languages) {
		$this->languages = $languages;
		return $this;
	}

	/**
	 * Get languages
	 *
	 * @return string
	 */
	public function getLanguages() {
		return $this->languages;
	}

	/*******************************************************************/

	/**
	 * Add dependencies
	 *
	 * @param \Tugel\TugelBundle\Entity\Package $dependencies
	 * @return Package
	 */
	public function addDependency(\Tugel\TugelBundle\Entity\Package $dependencies) {
		$this->dependencies[] = $dependencies;
		return $this;
	}

	/**
	 * Remove dependencies
	 *
	 * @param \Tugel\TugelBundle\Entity\Package $dependencies
	 */
	public function removeDependency(\Tugel\TugelBundle\Entity\Package $dependencies) {
		$this->dependencies->removeElement($dependencies);
	}

	/**

src/Tugel/TugelBundle/Resources/views/Default/about.html.twig
{% extends "TugelBundle::layout.html.twig" %}

{% block content %}
<div class="container">
	<h2>About</h2>
</div>
{% endblock %}

src/Tugel/TugelBundle/Resources/views/Default/formtest.html.twig
{% extends "TugelBundle::layout.html.twig" %}

{% block content %}
<div class="container">
	{#{ form(form) }#}
	{{ form_start(form) }}
		{{ form_row(form.submit) }}
		{{ form_row(form.submit2, {attr:{type:'success'}}) }}
		{{ form_row(form.submit3, {attr:{type:'danger'}}) }}
	{{ form_end(form) }}
</div>
{% endblock %}

src/Tugel/TugelBundle/Resources/views/Default/index.html.twig
{% extends "TugelBundle::layout.html.twig" %}

{% block html_attr 'class="cover"' %}

{% set hideNavbarSearch = true %}

{% block content %}
<div class="cover-wrapper" style="position:absolute; top:0; min-height: 300px;">
	<div class="cover-wrapper-inner">
		<div class="main-search">
			<div>
				<h2>Tugel</h2>
				{% include "TugelBundle::searchForm.html.twig" with {navbar:false} %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

src/Tugel/TugelBundle/Resources/views/Default/info.html.twig
{% extends "TugelBundle::layout.html.twig" %}

{% import "TugelBundle:Form:jsonTree.html.twig" as tree %}

{% block content %}
<div class="container">
	<h2><a href="{{ package.url }}">{{ package.name }}</a></h2>
	<h3>Platform: {{ platform.name }}</h3>
	<h4>Languages: {{ package.languages }}</h4>
	<h4>Version: {{ package.version }}</h4>
{% if package.license is not empty %}
	<h4>License: {{ package.license }}</h4>
{% endif %}
	<h5>ID: {{ package.id }}</h5>

	<div class="panel-group accordion" id="accordion" role="tablist" aria-multiselectable="true">
		<div class="panel panel-default">
			<a class="panel-heading" role="tab" id="descriptionHeading">
				<h4 class="panel-title">Description</h4>
			</a>
			<div id="description" class="panel-collapse collapse in" role="tabpanel">
				<div class="panel-body">
					{{ package.description is empty ? 'No description available' : package.description }}
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<a class="panel-heading" role="tab" id="dependenciesHeading">
    			<span class="badge">{{ package.dependencies|length }}</span>
				<h4 class="panel-title">Dependencies</h4>
			</a>
			<div id="dependencies" class="panel-collapse collapse" role="tabpanel">
				<div class="panel-body">
					<ul>
						{% for pkg in package.dependencies %}
						<li>
							<a href="{{ path('info_named', {platform:pkg.platform.name, package:pkg.name}) }}">{{ pkg.name }}</a>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<a class="panel-heading" role="tab" id="dependencyOfHeading">
    			<span class="badge">{{ package.dependencyOf|length }}</span>
				<h4 class="panel-title">Dependency of</h4>
			</a>
			<div id="dependency-of" class="panel-collapse collapse" role="tabpanel">
				<div class="panel-body">
					<ul>
						{% for pkg in package.dependencyOf %}
						<li>
							<a href="{{ path('info_named', {platform:pkg.platform.name, package:pkg.name}) }}">{{ pkg.name }}</a>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<a class="panel-heading" role="tab" id="tagsHeading">
    			<span class="badge">{{ tags|length }}</span>
				<h4 class="panel-title">Tags</h4>
			</a>
			<div id="tags" class="panel-collapse collapse" role="tabpanel">
				<div class="panel-body">
					{% set length = 3 * 400 %}
					{% if tags|length > length %}
						<h4>Too many tags! Displaying only first {{ length }} tags.</h4>
						{% set tags = tags|slice(0, length) %}
					{% endif %}
					<div class="row taglist">
						{% set cnt = (tags|length / 3)|round(0, 'ceil') %}
						{%- for i in 0..2 %}
						<div class="col-sm-4">
							<table>
								<tbody>
									{%- for tag,count in tags %}{% if loop.index0 >= cnt * i and loop.index0 < cnt * (i + 1) %}
									<tr>
										<td><span class="badge">{{ count }}</span></td>
										<td><a href="{{ path('search', {q:tag}) }}">{{ tag }}</a></td>
									</tr>
									{%- endif %}{% endfor %}
								</tbody>
							</table>
						</div>
						{%- endfor %}
					</div>
				</div>
			</div>
		</div>
		{% if explain is defined %}<br>{{ tree.tree(explain) }}{% endif %}
	</div>
</div>
{% endblock %}

src/Tugel/TugelBundle/Resources/views/Default/search.html.twig
{% extends "TugelBundle::layout.html.twig" %}

{% import "TugelBundle:Form:jsonTree.html.twig" as tree %}

{% block content %}
<div class="container">
{% if results is defined %}
	{% set q = 'library ' ~ (query.platform is defined ? query.platform ~ ' ' : '') ~ (query.language is defined ? query.language ~ ' ' : '') ~ query.query %}
	{% set q = q|url_encode %}
	<div style="font-weight:bold;"> |
		<a href="http://google.com/search?q={{ q }}">Google</a> |
		<a href="http://bing.com/search?q={{ q }}">Bing</a> |
		<a href="https://packagist.org/search/?q={{ query.query|url_encode }}">Packagist</a> |
		<a href="http://hackage.haskell.org/packages/search?terms={{ query.query|url_encode }}">Hackage</a> |
		<a href="https://pypi.python.org/pypi?%3Aaction=search&term={{ query.query|url_encode }}">PyPi</a> |
	</div>
{% if query.platform is defined or query.language is defined %}
	<h3>{% if query.platform is defined %}Platform:{{ query.platform|capitalize }}{% endif %} {% if query.language is defined %}Language:{{ query.language|capitalize }}{% endif %}</h3>
{% endif %}
	<hr>
	<ul>
		{% for id,package in results %}
		<li>
			<h4>
				<span class="pkg_score {{ package._percentScore > 0.66 ? 'score_green' : (package._percentScore > 0.5 ? 'score_orange' : 'score_red') }}">{{ package._score|number_format(3) }}</span>
				{#<a href="{{ path('info', {id:package.id}) }}">{{ package.name }}</a>#}
				<a href="{{ path('info_named', {platform:package.platform.name, package:package.name, q:query.raw}) }}">{{ package.name }}</a>
				<a href="{{ package.url }}"><span class="glyphicon glyphicon-link"> </span></a>
			</h4>
			<div>
				<span class="pkg_platform">{{ package.platform.name }}</span>
				<span class="pkg_version">{{ package.version }}</span> 
				<a class="pkg_google" href="https://google.com/search?q={{ package.name|replace({'com.':'', '.': ' ', ':': ' ', '-': ' '})|url_encode }}">G</a>
			</div>
			<p>{{ package.description[:250] ~ '...' }}</p>
		</li>
		{% endfor %}
		<hr>
		<p>Query time: {{ time }}</p>
		{% if app.environment == 'dev' %}
			{% if el_query is defined %}{{ tree.tree(el_query) }}{% endif %}
			{% if el_response is defined %}{{ tree.tree(el_response) }}{% endif %}
		{% endif %}
	</ul>
{% else %}
{% if query.platform is defined or query.language is defined %}
	<h3>{% if query.platform is defined %}Platform: {{ query.platform }}{% endif %} {% if query.language is defined %}Language: {{ query.language }}{% endif %}</h3>
{% endif %}
{% endif %}
</div>
{% endblock %}

src/Tugel/TugelBundle/Resources/views/Default/stats.html.twig
{% extends "TugelBundle::layout.html.twig" %}

{% import "TugelBundle:Form:accordion.html.twig" as accordion %}

{% block content %}
{{ parent() }}
<div class="container">
	<h1>Statistics</h1>
	{#<pre>{{ stats_ }}</pre>#}
	
{% for platform in platforms %}
	{% if loop.first %}{{ accordion.start(platform.name|capitalize, null, true) }}{% else %}{{ accordion.tab(platform.name|capitalize) }}{% endif %}
		<div>Package count: {{ platform.count }}</div>
		<div>Indexed package count: {{ platform.indexed_count }}</div>
		<div>Error package count: {{ platform.error_count }}</div>
		<br>
		{{ accordion.start('Most common tags', null, true) }}
			{% set items = platform.stats.combinedTags.buckets %}
			<div class="row taglist">
				{% set cnt = (items|length / 3)|round(0, 'ceil') %}
				{%- for i in 0..2 %}
				<div class="col-sm-4">
					<table>
						<tbody>
							{%- for tag in items %}{% if loop.index0 >= cnt * i and loop.index0 < cnt * (i + 1) %}
							<tr>
								<td><span class="badge">{{ tag.doc_count }}</span></td>
								<td><a href="{{ path('search', {q:tag.key}) }}">{{ tag.key }}</a></td>
							</tr>
							{%- endif %}{% endfor %}
						</tbody>
					</table>
				</div>
				{%- endfor %}
			</div>
		{{ accordion.tab('Most common licenses:') }}
			{% set items = platform.stats.licenses.buckets %}
			<div class="row taglist">
				{%- for i in 0..2 %}
				<div class="col-sm-4">
					<table>
						<tbody>
							{%- for tag in items %}{% if loop.index >= items|length / 3 * i and loop.index <= items|length / 3 * (i + 1) %}
							<tr>
								<td><span class="badge">{{ tag.doc_count }}</span></td>
								<td><a href="{{ path('search', {q:'license:\'' ~ tag.key ~ '\''}) }}">{{ tag.key }}</a></td>
							</tr>
							{%- endif %}{% endfor %}
						</tbody>
					</table>
				</div>
				{%- endfor %}
			</div>
		{{ accordion.tab('Last added packages') }}
			<div class="table-responsive">
				<table class="packagetbl table table-condensed table-hover table-striped table-bordered">
					<thead>
						<tr>
							<th style="width:66px;">ID</th>
							<th style="width:250px;">Name</th>
							<th style="width:150px;">Added date</th>
							<th style="width:120px;">Latest version</th>
							<th class="desc">Description</th>
						</tr>
					</thead>
					<tbody>
						{% for package in platform.last_added %}
						<tr>
							<td>{{ package.id }}</td>
							<td><a href="{{ path('info_named', {platform:package.platform.name, package:package.name}) }}">{{ package.name }}</a></td>
							<td>{{ package.addedDate|date('Y-m-d H:m:s') }}</td>
							<td>{{ package.version }}</td>
							<td class="desc">{{ package.description|raw }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		{{ accordion.tab('Last indexed packages') }}
			<div class="table-responsive">
				<table class="packagetbl table table-condensed table-hover table-striped table-bordered">
					<thead>
						<tr>
							<th style="width:66px;">ID</th>
							<th style="width:250px;">Name</th>
							<th style="width:150px;">Indexed date</th>
							<th style="width:120px;">Latest version</th>
							<th class="desc" style="min-width:100px;">Description</th>
						</tr>
					</thead>
					<tbody>
						{% for package in platform.last_indexed %}
						<tr>
							<td>{{ package.id }}</td>
							<td><a href="{{ path('info_named', {platform:package.platform.name, package:package.name}) }}">{{ package.name }}</a></td>
							<td>{{ package.indexedDate|date('Y-m-d H:m:s') }}</td>
							<td>{{ package.version }}</td>
							<td class="desc">{{ package.description|raw }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		{{ accordion.end() }}
{% endfor %}
	{{ accordion.end() }}
</div>
	
{% endblock %}